pub const USE_FAUCET_ALIASES: [&str; 2] = ["useFaucet", "use-faucet"];
pub const MASTER_ACCOUNT_ALIASES: [&str; 6] = ["masterAccount", "master-account", "useAccount", "use-account", "accountId", "account_id"];
pub const SEED_PHRASE_ALIASES: [&str; 2] = ["seedPhrase", "seed-phrase"];
pub const PUBLIC_KEY_ALIASES: [&str; 2] = ["publicKey", "public-key"];
pub const SECRET_KEY_ALIASES: [&str; 2] = ["secretKey", "secret-key"];
pub const USE_LEDGER_ALIASES: [&str; 4] = ["signWithLedger", "sign-with-ledger", "useLedgerKey", "use-ledger-key"];
pub const LEDGER_PATH_ALIASES: [&str; 2] = ["ledgerPath", "ledger-path"];
pub const INITIAL_BALANCE_ALIASES: [&str; 2] = ["initialBalance", "initial-balance"];
pub const NETWORK_ID_ALIASES: [&str; 2] = ["networkId", "network-id"];