name: Publish to npmjs.com

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Configure credentials
        run: |
          npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_REGISTRY_TOKEN }}
      - name: Publish to npmjs.com
        run: |
          npm publish https://github.com/near/near-cli-rs/releases/latest/download/near-cli-rs-npm-package.tar.gz
